 @url = http://localhost:3311
 
### GET ALL MEMBERS
GET {{url}}/members

### POST 

# Request
POST {{url}}/members
Content-Type: application/json

{
    "id": "323dha",
    "name": "John Doe",
    "age": 22
}

### DELETE MEMBER BY ID

DELETE {{url}}/members
Content-Type: application/json

{
    "id": "323dha"
}

